### ISSUE TITLE
"tmt test" kinda implies "test it" (imperative)

### ISSUE THREAD

**Issue by hroncok** [psss/tmt#10]
The problem with the world "test" (or "plan") is that it is both a noun and a verb. In a command, it implies imperative when I read it. I cannot help it, but I read `tmt test` as "tmt, please, run the tests".

A simple solution to this is to use plural ("tests", "plans"). In fact, it IMHO even makes more sense, as `tmt tests` implies "let's do something with the tests" and it lists all the tests (plural) by default.

**Comment by psss** [comment]
I see. That might be confusing at the first sight. Perhaps it's a question of time if/when one would get used to it. But I like your idea with using the plural as it makes the `tmt --help` less confusing. These commands sound very natural, even better than with singular:

    tmt tests ls
    tmt plans lint
    tmt stories coverage

Basically all of those by default handle all available objects.  Plus, since the abbreviated versions are also supported, we can always omit the extra letters if desired/lazy enough. This would also work with `tmt test create` which will be quite common use case. Plus one for this naming.

**Comment by psss** [comment]
It seems there are no objections. Going to change it in the proposed way.
