### ISSUE TITLE
Automate copr releases

### ISSUE THREAD

**Issue by psss** [psss/tmt#184]
It would be nice to have a fresh copr build created for each commit merged in to master. @lukaszachy recommends using `rpkg` with a spec file template.

* https://docs.pagure.org/rpkg-util/
* https://pagure.io/rpkg-util

**Comment by psss** [comment]
Another alternative seems to be using the `tito` tool:

 * https://github.com/rpm-software-management/tito

And `packit` should have a fresh support coming soon well :-)

**Comment by lachmanfrantisek** [comment]
> And `packit` should have a fresh support coming soon well :-)

Yes, that's true. We are nearly done with the support for two new triggers for copr-builds:
- releases
- push to the specified branch

We already have it on stage (e.g. https://github.com/packit-service/hello-world/commits/build-branch), but there are still some bugs to fix.

By now, it's only about setting the commit status -- so, no other visual response yet. We plan to create an issue on build failure.

A related issue is here: https://github.com/packit-service/packit-service/issues/239

You'll get a message from GitHub when it's ready since we need to ask for new permissions to be able to react to this event.

**Comment by psss** [comment]
@lachmanfrantisek, thanks for the pointers. This looks promising! Two questions:

Would it possible to include `git log --oneline` commits since the last release as well? In the changelog I currently see the following:

    %changelog
    * Wed Apr 01 2020 Packit Service <user-cont-team+packit-service@redhat.com> - 0.72-1.20200401173946056633
    - Development snapshot (54ee6209)

And second: Will it be possible to configure a different copr repo for pull request testing (can remain as temporary repos under packit) and for commits to master (should go to the production copr repo).

**Comment by lachmanfrantisek** [comment]
> Would it possible to include `git log --oneline` commits since the last release as well?

We already have an issue for it: https://github.com/packit-service/packit/issues/738

> Will it be possible to configure a different copr repo for pull request testing (can remain as temporary repos under packit) and for commits to master (should go to the production copr repo).

It should be possible now, you can specify that per job: https://packit.dev/docs/configuration/#supported-jobs

**Comment by psss** [comment]
That's great, @lachmanfrantisek. Looking forward to the bright future! :-)

**Comment by psss** [comment]
Bulding in copr has been enabled some time ago in 8060c7aff1c8a41603c9112d5cfccef85590d645 and  8060c7aff1c8a41603c9112d5cfccef85590d645.
