### ISSUE TITLE
For virtual cases make `path` to be parent's path by default

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#239]
Use case: One test script, several cases with different attributes (e.g. require, environment...)

Idea was to:
1. create directory, place test code there
2. create main.fmf with common attributes/defaults (contact, summary, duration...), No real test case is represented by main.fmf
3. create separate fmf file for each case

I've created 1. with `beaker-wizard` and 2. with `tmt tests import` but let's focus on the future (templates or manual edit of fmf)

Problem was that `path`, which is used by executor (change to this dir and execute test script there) is not mandatory field which defaults to `self.name`.
However for **virtual** cases it such directory does not exist and parent's path should be used and I can't think of scenario where it would match.

Current workaround is to add path to 'main.fmf' however
1. One needs to remember that
2. It's annoying typing for something which is easily detectable

Proposal:
Make `path` default to parent's path for virtual cases, keep name for 'real' case.

Please do not depend on correct import or templates for setting path to main.fmf - To keep easy drop-in metadata files instead of creating own templates.

**Comment by lukaszachy** [comment]
Thank you for the chat, @psss. 
The conclusion of the chat was that this needs broader discussion with users as such change will break what is currently possible:
Keep metadata above test code and depend that path changes as does the name.
So it boils down to the question what is more common and easier to explain to the end user.

**Comment by psss** [comment]
So the solution could be to update the L1 specification to say that if the `path` is not specified directory where the metadata file is stored would be used. We would probably need to extend `fmf` to provide this information, because for now there is only available list of source files from which the metadata were aggregated.

However this approach breaks the following case: When using elasticity to define multiple tests in a single file higher in the directory structure one would have to explicitly specify paths for each test.

**Comment by lukaszachy** [comment]
Referencing `+1` from https://github.com/psss/tmt/pull/240#issuecomment-628645112

We will see on the workshop what users expect.

**Comment by lukaszachy** [comment]
On hacking session this change was approved, I'll create PR.
Hint: Use 'sources' attribute of the node.
