### ISSUE TITLE
Support reboot in the internal tmt executor

### ISSUE THREAD

**Issue by psss** [psss/tmt#281]
Yesterday during our discussion @thrix mentioned that it would/should not be too hard to implement support for reboot in the internal tmt executor. Let's brainstorm more if this would make sense or if we should leave it to the future `restraint` plugin, see #197. How it could work?

 * Test finishes with an agreed exit code or message on the output (going to reboot the guest)
 * Wait a bit until the ssh connection is back again
 * Start the last test again, optionally providing an extra environment variable

or

 * Test finishes with the message (please, reboot the guest for me)
 * Executor takes care of rebooting the system
 * The rest is the same as above

As far as I know, the reboot count is already handled somehow by beakerlib, so perhaps there's nothing more to do, but if needed `tmt` could also export an environment variable `TMT_REBOOT_COUNT` or something similar. End of initial brainstorm.

**Comment by lukaszachy** [comment]
Early feedback
- Keep compatibility with restraint (since it is still main harness) and it will make it easier for tests - Write them so they work in restraint and they work everywhere)
- Be careful about provision:localhost
- Not sure if it is possible with provision:container

**Comment by kkaarreell** [comment]
Except the system reboot that is being (somehow) advertised by the test, it should also handle temporary network outage, e.g. due to network being restarted. I am not sure whether this should be handled via fmf metadata (announcing the need of reconnect/retries/delay) or via test (announcing network outage).

**Comment by AloisMahdal** [comment]
Slight alteration of the above approach:

 *  test calls a command that means "i want to restart"

this command informs TMT executor to kill the test (~ like /usr/sbin/reboot would), orchestrate the actual reboot (with extra steps if needed for CI -- just like `rhts-reboot` would) and after the reboot, bring back the same test (with `REBOOTCOUNT`-like envvar, just like `rhts-reboot` would).

rstrnt/rhts compatibility could be achieved by symlinking the command to the TMT version.  (And having the same CLI, or altering CLI syntax based on `argv[0]`.)

**Comment by pvalena** [comment]
> Early feedback
> 
>     * Keep compatibility with restraint (since it is still main harness) and it will make it easier for tests - Write them so they work in restraint and they work everywhere)
> 
>     * Be careful about provision:localhost

Agreed.
This may be mitigated by actually relaying/delegating the reboot to a `provision` step (the object) via some API. It may be just an implementation detail, but I'd like to avoid simply running `reboot` from `execute` step.

> 
>     * Not sure if it is possible with provision:container

There's no reason not to realize this, when implemented via `provision` (container restart).

**Comment by rh-mcermak** [comment]
This is sort of a blocker for testing components such as systemtap or perf, which need kernel debuginfo, devel, headers etc respective to the *running* kernel. Practice shows that the *configured* repos don't have kernel debuginfo, devel, headers etc respective to the *running* kernel. A work around to this is to update the test worker, reboot it, and then the needed packages "show up" in the configured repos, so that testing can successfully continue. This however requires support for rebooting the test worker.

**Comment by Athwale** [comment]
This seems to be breaking CI whenever a test reboots a machine. Blocking the competition and requiring manual kill of the machine.

**Comment by psss** [comment]
Just a short note to today's discussion: Instead of introducing two new methods of the `Guest` class I would suggest to add a single method `Guest.reboot()` which would have an optional parametr `Guest.reboot(hard=True)` for hard restart.
