### ISSUE TITLE
tmt test import should make sure `runtest.sh` is executable

### ISSUE THREAD

**Issue by thrix** [psss/tmt#378]
We are getting reports from users that some tests have `runtest.sh` not executable. The importing adds

```
test: ./runtest.sh
```

Which then for the user breaks. Seem the best option is to fix this during the import via:

* making the file executable

or 

* adding it as
```
test: bash runtest.sh
```

Or some other approach. This must work for the end user.

**Comment by thrix** [comment]
CC @hegerj @lukaszachy @Jakuje

**Comment by Jakuje** [comment]
I think we should go the first way to make sure all the migrated tests are executed the same way. Differences in `test:` might be confusing later.

**Comment by psss** [comment]
Agreed, `tmt test import` could check the script permission and fix if needed.

**Comment by hegerj** [comment]
I had no idea that the value of `test` parameter is directly executed.
It should be no trouble putting permission adding into the importing process unless someone is against it.

**Comment by thrix** [comment]
I do not see why that would be a problem to anybody, but let's wait a bit for feedback :)

**Comment by pvalena** [comment]
> We are getting reports from users that some tests have `runtest.sh` not executable. The importing adds
> 
> ```
> test: ./runtest.sh
> ```
> 
> Which then for the user breaks. Seem the best option is to fix this during the import via:
> 
>     * making the file executable

I agree there could be some "best-effort" fix, like the above, or you can simply fail the execution.
But it doesn't even need to be always a file, right?

> 
> 
> or
> 
>     * adding it as
> 
> 
> ```
> test: bash runtest.sh
> ```

Please let's avoid this, because you cannot rely on every shell script to be written in bash (and also there's a `bash` path to resolve). It could also be other interpreter/executable - `python`/`ruby` f.e..

> Or some other approach. This must work for the end user.

I see the `test:` entry as a `test-related` metadata. It depends completely on the _framework_, what to do with it.

With `shell`, I'd simply say to `execute` is what should be expected (It even has to be in form of a local path `./runtest.sh` to work). Personally I expect the executor to do something like this:  `bash -c "$VALUE"` - for any arbitrary `test: $VALUE', and nothing more.
