### ISSUE TITLE
Import environment variables from Makefile

### ISSUE THREAD

**Issue by Jakuje** [psss/tmt#380]
There are several tests specifying environment variables in Makefile for various reasons. One of them is ignoring AVC errors:

> AVC_ERROR=+no_avc_check

At this moment, the `tmt import` considers only environment variables from Nitrate. I believe it should consider also the Makefile ones to increase compatibility.

**Comment by psss** [comment]
It makes sense to me to import environment variables from the `Makefile` as well. I would suggest that variables imported from the nitrate `arguments` field should override those detected from `Makefile`.

**Comment by hegerj** [comment]
@Jakuje @psss do we really want env variables set by Makefile to be overwritten by Nitrate `Arguments` value rather then added to it?
I ask because only variable set in Makefile I ever saw is the one given in first comment  `AVC_ERROR=+no_avc_check` which is not set in Nitrate (to my knowledge) and if there is to something else in Nitrate `Arguments` this variable would be again ignored.

**Comment by psss** [comment]
By override I meant just the order of filling the `data` dictionary during the import. I would check `Makefile` first and then add variables from `Arguments`. So if `AVC_ERROR` is defined in `Nitrate` it would override what's in the `Makefile`. But other variables should not override it.

**Comment by hegerj** [comment]
I see, that makes more sense :)
