### ISSUE TITLE
New tmt command for performing clean up actions

### ISSUE THREAD

**Issue by psss** [psss/tmt#436]
It would be nice to have a comfortable way to clean up unused stuff like old run workdirs or shut down forgotten/abandoned virtual machines or containers. Let's brainstorm possible features first.

To handle run workdirs:

    tmt clean run --last
    tmt clean run -i ID
    tmt clean runs --old
    tmt clean runs --all

To cleanup abandoned containers/machines:

    tmt clean guests
    tmt clean guests --container
    tmt clean guests --virtual
    tmt clean guests --all

Remove downloaded images from the disk:

    tmt clean images

Does it look reasonable?

**Comment by thrix** [comment]
what does `--old` do?

**Comment by psss** [comment]
> what does `--old` do?

That one could remove old test run workdirs. Let's say anything older than one week? Not sure what the default should be. Or it could leave just the latest 100 jobs? Could be something you would put into your `crontab`.

**Comment by thrix** [comment]
that is why I am asking, not sure about it, I would not have `--old` or have it with an option `--older week`, `--older day` ?

**Comment by FrNecas** [comment]
I will try to implement it, should be fairly similar to `tmt status`

**Comment by psss** [comment]
Thanks for taking this. Probably would be good to discuss the outlined syntax on the hacking session tomorrow.

**Comment by FrNecas** [comment]
Sure, sounds good. I will think about the syntax and perhaps extend your initial proposal and we can discuss it tomorrow.

**Comment by FrNecas** [comment]
A few notes:

The whole command should probably offer `--dry` option to only list what would be done since we are dealing with removing data.

`tmt clean run(s)`
 - We should also support specifying the "root" directory which will be searched if `--id` isn't provided (similar to `tmt status`). So perhaps `tmt clean run .` to clean runs from CWD?
 - Cleaning old runs sounds great, the question is how it should be specified. I am not very keen on just `--old` with a default, a user may want to modify the behaviour based on their needs. Perhaps `--keep N` to keep the latest N runs and remove the rest? This is probably the easiest to use (no need to specify a special format for date or similar).
 - is `tmt clean runs --all` really necessary? I'd assume `tmt clean run(s)` would clean all runs if `--keep`/`--id`/`--last` are not specified.

`tmt clean guests`
- again, is `--all` really necessary?
- since guests are tied to runs, we should probably also offer options similar to `tmt clean run` for run selection, `--last`, `--id`, specify root (`tmt clean guests .`) and perhaps even selection of old runs (not sure if that would be to any use).

`tmt clean images`
- Not very sure about this one. As for containers, we can't really distinguish images pulled by tmt from the others, or can we? As far as I can see, only testcloud provision uses a special location to save images where we can easily delete them from. Or am I missing something?

**Comment by frantisekz** [comment]
FYI: testcloud has recently gained an ability to cleanup its storage, with configurable space limit, deleting the oldest images that are not used by any instance, running or shut off once the threshold is reached.
