### ISSUE TITLE
tmt export and tmt lint should verify that the fmf url is valid

### ISSUE THREAD

**Issue by thrix** [psss/tmt#481]
We are seeing cases when people mess up FMF url or it is invalid. Users are then sad when the test breaks in CI.

It would be awesome if tmt export or even tmt lint could support this, so this does not go unnoticed. In theory CI could even run `tmt lint` to make sure the metadata is correct. Note that we seen examples when the FMF url was a fork and got removed later on ...

**Comment by lukaszachy** [comment]
Or when user exported from local-only changes in dist-git and forgot to push to origin.

IMHO `tmt tests export --nitrate` should verify that `ref` it uses exists on `url` it asks for.

**Comment by lukaszachy** [comment]
Note from the hacking session: Sanity of fmf-id should be verified by running `fmf.base.Tree.node(fmf_remote_id)`. It will download and load fmf-id as `wow` (or any other tool reading it) should. Any tracaback during its call should be an Error and stop the export to nitrate.

So one has to do `git push` to have all bits on remote first and just then do the export. Otherwise there would be a risk of race condition between export and scheduling tool.

**Comment by thrix** [comment]
I will try to contribute with this

**Comment by thrix** [comment]
Seems `git remote-ls` should help here, we will see. Looks promising

**Comment by lukaszachy** [comment]
Just to recap. export should exit with  error if `remote id` doesn't exist or if metadata on remote are different to local.
Otherwise user will be disappointed either in scheduling or in test review :)
Especially 3. can get ignored and provide false results.

Ideas how mismatch can happen:
1. user forgot to add .fmf/version -> remote is not fmf structure
2. user forgot to commit test .fmf files -> remote doesn't contain node
3. user forgot to commit _changed_ fmf files -> remote contains unchanged data

**Comment by psss** [comment]
@lukaszachy from the description it sounds like this issue if focused at `tmt test`. I see @thrix is improving `tmt plan lint` in #550. So we still need to cover the `tmt test` part, right? I'm not completely sure we should block 1.3 on this.

**Comment by psss** [comment]
Agreed on the hacking session to move to the next release.

**Comment by psss** [comment]
@lukaszachy, @thrix, if I remember correctly, we agreed on the hacking session to not block 1.4 on this? Is that right/ok?
