### ISSUE TITLE
tmt import --nitrate imports just a single test case

### ISSUE THREAD

**Issue by sopos** [psss/tmt#528]
I have 4 test cases with script _/CoreOS/rsyslog/Multihost/bz701782-rsyslog-TLS-does-not-encrypt-traffic-on-s390x-and_ but `tmt tests import --nitrate` creates just one test in the _fmf_ format.

**Comment by hegerj** [comment]
The reason why import ignores those nitrate cases is because they have spaces in their `script` variable. If you remove those it should work.
Alternatively we could use `script__contains` when searching, then it would be enough for the searched script to be substring to match. What do you think @psss ?

**Comment by sopos** [comment]
I do not see spaces in the script field. e.g. TC#607999

**Comment by psss** [comment]
>  Alternatively we could use `script__contains` when searching, then it would be enough for the searched script to be substring to match. What do you think @psss ?

I think that could work:

  * fetch all matching
  * strip white space
  * filter only fully matching ones

Not sure how common this can be and if it would be worth it.

**Comment by hegerj** [comment]
I did some exploring with Nitrate cases and I haven't found enough such cases to warrant changing the code. I recommend not altering the code right now and see if something changes in the future.
