### ISSUE TITLE
Library set ref to master as default

### ISSUE THREAD

**Issue by lukaszachy** [psss/tmt#530]
This will be a problem once psss/fmf/pull/104 is accepted.
We should treat no set ref as default_branch

https://github.com/psss/tmt/blob/ecd29647cd4003f39e1d0c5dff66bf3f4311f1e2/tmt/beakerlib.py#L64

Maybe time to split fmf.fetch and use its parts for all git-related operations?

**Comment by lukaszachy** [comment]
For the context: https://fedoraproject.org/wiki/Changes/GitRepos-master-to-main 
So if one uses fmf reference, or renames default branch on github this will bug will hit.

**Comment by psss** [comment]
So what about extending the `fmf.utils.fetch()` function to accept destination directory as well? This would nicely cover the beakerlib library fetching as well. Instead of doing *clone* and *checkout* in two steps, `tmt.beakerlib.Library.fetch()` would leave all the work to `fmf.utils.fetch()` and handle possible exceptions.

**Comment by lukaszachy** [comment]
Seems like a good idea. Please check https://github.com/psss/fmf/pull/106 if it makes sense.
I'll try to use it in PR for this issue.
