### ISSUE TITLE
New user's feedback

### ISSUE THREAD

**Issue by befeleme** [psss/tmt#739]
Hey, 
as I new user who wants to use tmt for testing the Fedora Python packages (primarily using Fedora CI), I came across various issues I'd like to summarize here. Also, my questions were already answered by the people knowing tmt better (thank you for the support!) and after a few days I feel I got a basic grasp of what and how to do. And I believe the new user experience could be improved.

1. System mental model
When I tried the basic examples, I was left with a bunch of files but no mental model what I **should** do to create a more robust working system. The gap between The first steps and the Specification is big.
Which files are mandatory to have running tests? How should the project be structured?
Do I need a plan? What is a relationship between the plan and test? 
Provided there is a single plan (covering logical part of the tested area) how should I write the tests? 
Should I create one fmf test file per test case or gather all test scripts under one `main.fmf`? 
Is it ok to write the test script directly in the "test fmf" file or in "plan fmf" file?
Is there any recommended design setup to follow? -- Here I would be super happy to see even some basic graphs, just to understand the mental model behind the tool. 

2. Specification
Specification lists 4 metadata levels. Is each of them supposed to be a separate file?
Given for example specification of [Core](https://tmt.readthedocs.io/en/latest/spec/core.html) I'm left with a naive question: if I wanted to use it, where should it be stored and how should it be named? How will tmt recognize it?
In many cases in the docs it's not entirely clear what file/part of the project is used, see last example in [Context](https://tmt.readthedocs.io/en/latest/spec/context.html#trigger) - `adjust` & `enable` were documented in Core, the rest looks like from Plan. Having the examples explicitly named would be really helpful. (The same caveat have the slides from [devconf](https://static.sched.com/hosted_files/devconfcz2021/37/tmt-slides.pdf)).

3. Real-life examples
It would be handy to see a reference example project covered with more robust test suite where it would be easy to understand what role the particular levels play.

Side note: 
I didn't encounter an explanation of `+` which is sometimes present in the examples, searching for `+` or `plus` doesn't help. 
```
adjust:
  - environment+:
        SH: bash
```

That said, thanks for the good work on this tool! The amount of use cases you're aiming to cover is much wider than I might ever encounter. I appreciate the convenience of working with tmt on my machine. I do hope the feedback gives a clear picture of a newbie mind in this labyrinth and I'll be happy to discuss it further.

**Comment by lukaszachy** [comment]
Thank you very much for your feedback @befeleme. 

Just in the case someone finds this issue before tmt documentation is updated: `+` is feature of fmf and as such is documented at https://fmf.readthedocs.io/en/stable/features.html#merging

**Comment by jscotka** [comment]
@lukaszachy as you suggested, but not sure if described well e.g. in case:
 - in tests there is not defined `+` or just doe some of them -> probably not defined in doc, that if in this case `item` and `item+` behaves same or `item+` will be ignored if not defined `item` in parents
 - how it behaves inside TMT, in sense if there is special handling, e.g. `adjust: prepare:` if I do not define `prepare` inside `plans` but just as part of `adjust`, if it removes all default preparations (like package installation) so that `prepare+` is much safer in this case?

**Comment by psss** [comment]
@befeleme, thanks a lot for summarizing the documentation gaps from a new user point of view. This is highly appreciated.

> The gap between The first steps and the Specification is big.

Yes, completely agreed. I believe that's mainly because we've just started with writing the guide (single chapter only as for now). The plan is to have the nice walkthrough for new users covered by the guide and use the specification section for technical details which will be linked at many places from the guide.

I'm just about writing the second chapter of the guide this week. From what you've written, I'd say the best content for the second chapter would be to give an explanation of what the test, plan (and story) are, how they are used and what is their relation. So I propose we cover the following of your questions in the new chapter:

 * Which files are mandatory to have running tests?
 * How should the project be structured?
 * Do I need a plan?
 * What is a relationship between the plan and test?
 * Is there any recommended design setup to follow?
 * Where should the files be stored and how they should be named?
 * How will tmt recognize a specific metadata levels (plan/test/story)?

@befeleme, do you agree? Or would you propose a different content? @pirat89, I remember you also had a feedback related to the metadata levels description. Is there anything you would like to add?

**Comment by pvalena** [comment]
FTR. there's a talk from DevConf.CZ (not sure if that was meant with the slides): https://www.youtube.com/watch?v=HVo4iS1XOuo&list=PLU1vS0speL2YQ9WXMnY-glVErAIsTsSAl&index=30&ab_channel=DevConf 

Maybe it can help with the metadata+examples.

**Comment by befeleme** [comment]
@psss, this sounds great, I have no remarks to the proposed contents. 
@pvalena, thank you for the link. I'll take a look.
