### ISSUE TITLE
Flexible rhts test Makefile->Type to tag conversion

### ISSUE THREAD

**Issue by juk** [psss/tmt#759]
The idea is to let user to convert "Type" field from the rhts test Makefile into tags section of main.fmf
This would require some filtering like: 
* consider ","  "/"  "\s" as dividers
* types like: kerneltier1, KernelTier1, kernelTier1 should be converted into KernelTier1
* accept "."  "_"  and "-" in the type name, for ex Multihost.1.3 or gre_offload

This feature would eliminate a lot of extra work with setting tags when importing tests from existing repo.

**Comment by psss** [comment]
We've shortly discussed this on the hacking session yesterday. The problem is that not everybody needs/want to import the `Type`. The best solution (for the future) could be to allow users to enable features like this in their config (together with regexp matching rules and similar stuff).

For now the proposed solution is to introduce a new option, let's say `--type` which would explicitly enable the `type -> tag` conversion. It could be a list of types which should be converted to corresponding tag. The default would be `multihost` as that's the current behaviour:

    tmt test import --type multihost

Not sure about the lowercase/uppercase/camelcase handling. Probably I would recommend that the desired tag name would be provided in the option and it would catch/match case-insensitive all detected types. So for the @juk's use case it would be:

    tmt test import --type KernelTier1

Which would cover `kerneltier1`, `KernelTier1` and `kernelTier1` variants. Optionally, a special key could be supported to convert all detected types:

    tmt test import --type all

@lukaszachy, @FrNecas, @hegerj, @dkarpele, @juk, what are your thoughts on this?

**Comment by psss** [comment]
@juk, ok, thanks for the feedback. Should be quite easy to implement. @lukaszachy, @FrNecas, @hegerj, @dkarpele, anybody willing to look into this? Any other comments or suggestions here?

**Comment by dkarpele** [comment]
Hi, I will take a look on this issue.

**Comment by dkarpele** [comment]
Hi @psss,
to clarify, I think it should be done like this:
`tmt test import` = `tmt test import --type multihost` (current behaviour tmt/convert.py#334)
`tmt test import --type` = `tmt test import --type multihost`
