### ISSUE TITLE
Add a plugin example to the documentation

### ISSUE THREAD

**Issue by psss** [psss/tmt#760]
In order to help contributors with writing new plugins it would be nice to document a simple/minimal example of a step plugin. Here's an [example for inspiration](https://rebase-helper.readthedocs.io/en/latest/user_guide/writing_plugins.html#example).

**Comment by RHEmployee** [comment]
Hello. If still free I would like to work on it however after some study I would like to ask:
what is plugin? :)
I see that there is discovery step which contains for example shell.
I have experience only with minute.py plugin(?) which is part of provision step.
So what this example plugin should contain? Only provision part? Or should I create example for each step which doesn't look that easy for now (no knowledge for now :)). So I just would like to ask this "stupid" question before I start implement whole new wheel :).

**Comment by FrNecas** [comment]
Plugin in this context is an "alternative implementation" of a step. So minute is indeed a plugin of the provision step. IMHO there is no point in creating an example for each of the steps, what I personally would like to see:
 - a quick introduction to the whole concept of steps/plugins, maybe some description of the architecture, inheritance, etc. (that is already partly covered by the docs but could be expanded and tailored to the use-case of writing new plugins)
 - an overview of the available steps and a list of methods that must be overridden in order to create a new plugin for each of the steps (e.g. the guest method of Provision https://github.com/psss/tmt/blob/master/tmt/steps/provision/__init__.py#L160)
 - a very simple example of one plugin for one step that will demonstrate the main concepts (that you have to inherit, override methods, etc. etc.)

**Comment by psss** [comment]
>  what is plugin? :)

Each step provides (or can provide) several ways of implementation. For example for the `provision` step there is `container` method implemented by the `podman` plugin. The plugin is basically the class inheriting from the `Plugin` class, or more precisely from respective step plugin class, for example from the `ProvisionPlugin` class.

> So what this example plugin should contain?

I don't think we need to document plugins for all steps. I guess we could start with just one or two. The `discover` and `provision` steps seem like a good candidates to me. @FrNecas, @lukaszachy, what do you think?

**Comment by RHEmployee** [comment]
About documentation:
where it should land?
It looks like docs/examples.rst is right place. 

About inheritance:
I just steal from minute plugin so I need to take a look at shell and fmf discovery steps.

**Comment by RHEmployee** [comment]
Hello.

Partial documentation is now in docs/plugins.rst.

@FrNecas About:
maybe some description of the architecture, inheritance, etc.

I personally don't like implementation details in documentation which can be clear from code.
Overall architecture would be great however I don't think I'm right person to do that for now.

Example plugin has been extend with comments from upper classes so now it should be clear from just looking at plugin. I can be wrong, but I'm pretty happy when I see all comments on one place :).
