### ISSUE TITLE
User confusion when tmt-provision-virtual is not installed.

### ISSUE THREAD

**Issue by RHEmployee** [psss/tmt#811]
Hello.

I just received reproducer for possible image bug in form of:

$ tmt run  provision -h virtual -i file://1MT-RHEL-9.0.0-20210613.4-Beta.qcow2
-vvv -ddd login

and I received:
Usage: tmt run provision [OPTIONS]
Try 'tmt run provision --help' for help.

Error: no such option: -i

So I was confused...

Help shows:
$ tmt run provision -h virtual --help
Usage: tmt run provision [OPTIONS]

  Provision an environment for testing or use localhost.

  Supported methods (virtual by default):

  connect .............. Connect to a provisioned guest using ssh
  local ................ Use local host for test execution
  minute ............... Provision guest using 1minutetip backend
  minute.obsolete ...... Provision guest using 1minutetip backend

so it's ok? There is virtual missing in list but is present in: Supported methods.

Then:
$ tmt run  provision -h virtual
/var/tmp/tmt/run-013

/plans/features/advanced
    hint: Install 'tmt-provision-virtual' to run tests in a virtual machine.
    hint: Use the 'local' method to execute tests directly on your localhost.
    hint: See 'tmt run provision --help' for all available provision options.
Unsupported provision method 'virtual' in the '/plans/features/advanced' plan.

Just give me great tip what is wrong with my system :).

**Comment by psss** [comment]
Hm, so what should we recommend to the user when `tmt-provision-virtual` is not available? The `provision` step method defaults to `virtual` but the plugin is not available with the "default" install using `dnf install -y tmt`. I don't think it would be good to default to `local` as this could break user's laptop...

```
tmt run provision -h virtual --help
```

I believe the command above should report an error if the `virtual` method is not available. Something like "Sorry, virtual is not available, but we have this and this... Or you can install that". @lukaszachy, @FrNecas, what do you say?

**Comment by FrNecas** [comment]
@psss Agree with your point on the default. With only `tmt` installed, there is only connect, local and minute obsolete neither of which make sense to use as a default for testing.

We could try to somehow fix the error messages so that they give information about the provision plugins but I am not completely sure how feasible is that. It probably comes from internal logic of click that will be difficult to work around. But we can certainly try.

Lastly, I thought of a dirty but more user-friendly approach which slightly goes against the principle of dynamic plugins and how they are implemented in tmt. We could store the list of all supported methods even if they are not installed on the system. E.g. even with only `tmt` package installed, we would know that there exists ` virtual` method and `tmt run provision --help` could mention the unsupported methods and how they can be installed.

**Comment by psss** [comment]
I think the last suggestion makes sense. Btw, we already have a few hints implemented [here](https://github.com/psss/tmt/blob/master/tmt/steps/__init__.py#L301).

**Comment by lukaszachy** [comment]
Do we have to have 'default' method? YMMV but I always either specify image (so I'm forced to specify --how as well), container or connect methods. And in CI "connect" is used (so provision in plan is ignored).

Hint with possible methods will be nice, but isn't it better to point to the documentation or `dnf search tmt-provision`? With hardcoded hints private provisions plugins will never be listed.

**Comment by psss** [comment]
> isn't it better to point to the documentation or `dnf search tmt-provision`

Good idea!

> Do we have to have 'default' method?

I think so. I find `tmt run` or `tmt run provision login finish` as a "nice" use cases :)
