### ISSUE TITLE
Multiline shell scripts

### ISSUE THREAD

**Issue by psss** [psss/tmt#818]
When a multi-line string is used as a shell script it is executed line by line and the exit code is taken from the last command. If such script is used as a test script, it can mask possible failures. Happened recently in the [pipenv](https://src.fedoraproject.org/rpms/pipenv/pull-request/38) project. Example config:

```yaml
execute:
    script: |
        /bin/false
        /bin/false
        /bin/true
```

Execution silently passes:

```
> tmt run -av provision -h container
/var/tmp/tmt/run-005
Found 1 plan.

/plans/example
    discover
        how: shell
        directory: /tmp/exit
        summary: 1 test selected
            /script-00
    provision
        how: container
        image: fedora
        name: tmt-var-tmp-tmt-run-005-plans-example
        distro: Fedora 34 (Container Image)
        kernel: 5.12.12-300.fc34.x86_64
        summary: 1 guest provisioned
    prepare
        summary: 0 preparations applied
    execute
        how: tmt
            00:00:00 /script-00 [1/1]
        summary: 1 test executed
    report
        how: display
            pass /script-00
        summary: 1 test passed
    finish
        container: stopped
        container: removed
        summary: 0 tasks completed

total: 1 test passed
```

Would it possibly make sense to use `set -eux` by default for multiline shell scripts? Or shall we just explicitly document/warn that for multi-line shell scripts only the last command exit code is checked?

**Comment by hroncok** [comment]
As a CI user, I expect at least `set -e` is the default for multiline commands.

**Comment by hroncok** [comment]
For example [GtiHub Actions use the following options for `run:` by default](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#using-a-specific-shell):

    bash --noprofile --norc -eo pipefail

**Comment by encukou** [comment]
Someone will be surprised by either behavior, but the risk analysis is pretty clear, IMO:
* If you expect failures in subcommands are OK, but they aren't, you'll get test failure and will need to change tests. I don't think that's a big deal.
* If you expect failures in subcommands fail the test, and they don't, your tests are worthless and you don't get any notification about it. That's pretty bad.

> Or shall we just explicitly document/warn that for multi-line shell scripts only the last command exit code is checked?

Even if someone reads that part of the docs, they likely won't remember the detail when they need it. It's better if they document this behavior explicitly in the test definition (with `set +e`).

**Comment by jscotka** [comment]
It is very hard to know the defaults. and I think it is completely okay to add at the beginning of your multiline script
`set -eux` than do it by default.

Because when I use it I have to know that there is some default  and in ideal case TMT so clean from definition that nobody needs to read the documentation. and when using multiline I expect it behaves as bash.

So from that perspective I think that explicit is better than implicit in this case  if I want to have ther some `set -e`

But I understand that it is safer option than that some will expect this behaviour and will not get it and someone who don't expect it, can fix it explicitly by `set +e` that's true. 

question is if similar examples will lead to well readable code. 
I can imagine that usecase of this scenario is more less closer to this usecase, just simplified everything to test, or maybe using these multilines inside tests because unable pass though some env vars, from preparation steps (but in this case it is probably expected that there will be fails like `if cond; then; A=0; else; A=1; fi`) or some `command && A=1 || A=0`
```
prepare:
  - name: prepare one
     script: /bin/false
  - name: prepare two
     script: /bin/false
execute:
    script: /bin/true
````

**Comment by psss** [comment]
I believe @encukou provided the key/essential point here:

> If you expect failures in subcommands are OK, but they aren't, you'll get test failure and will need to change tests. I don't think that's a big deal.

This will help to prevent overlooking unexpected failures in the code, so `set -eo pipefail` seems like a reasonable default to me.

**Comment by jscotka** [comment]
> I believe @encukou provided the key/essential point here:
> 
> > If you expect failures in subcommands are OK, but they aren't, you'll get test failure and will need to change tests. I don't think that's a big deal.
> 
> This will help to prevent overlooking unexpected failures in the code, so `set -eo pipefail` seems like a reasonable default to me.

Yes, exactly I've mention it as well. that it is safer option.

But could be harder especially using `-o pipefail` because lots of people uses `failed_command || /bin/true` to avoid raise exception in case using `set -eux` and then could be harder debug what happened. What is reason to look into tmt documentation, when bash script fails?
Maybe it has to be very clear at least in verbose or debug mode, that it uses this option, and you have to override it by setting own `set` command. Because I do not see reason to look into tmt doc and search there explanation when my bash script what I test in bash and works, should not work well as charm inside TMT.

I've hope I've explained well my feeling of override some bash default settings.

**Comment by psss** [comment]
Yes, as part of the fix/change we document well the new default. Regarding multiple commands: This still can be useful if you want to see a nice overview of what passed and what failed as each of the script commands is handled as a separate test:

```yaml
summary: Basic smoke test
execute:
    script:
      - 'true'
      - 'false'
      - 'true'
      - 'true'
```

And the corresponding output:

```
/plans/example
summary: Basic smoke test
    discover
        how: shell
        directory: /tmp/multiple
        summary: 4 tests selected
            /script-00
            /script-01
            /script-02
            /script-03
    provision
        how: local
        distro: Fedora 34 (Workstation Edition)
        kernel: 5.12.13-300.fc34.x86_64
        summary: 1 guest provisioned
    prepare
        summary: 0 preparations applied
    execute
        how: tmt
            00:00:00 /script-00 [1/4]
            00:00:00 /script-01 [2/4]
            00:00:00 /script-02 [3/4]
            00:00:00 /script-03 [4/4]
        summary: 4 tests executed
    report
        how: display
            pass /script-00
            fail /script-01
            pass /script-02
            pass /script-03
        summary: 3 tests passed and 1 test failed
    finish
        summary: 0 tasks completed

total: 3 tests passed and 1 test failed
```
