### ISSUE TITLE
Spaces are not escaped in string env variables passed with "--environment"

### ISSUE THREAD

**Issue by juk** [psss/tmt#940]
Example of the command line
$ tmt run --all --environment BZLIST='716540 771869' plan --name /plans/Regression provision --how minute --image rhel-8
/var/tmp/tmt/run-007
Invalid variable specification '771869'.

**Comment by lukaszachy** [comment]
Hm, unfortunately this looks like a limitation of click (or python).

```python
import click
@click.option("-e")
@click.command()
def m(e):
    print(repr(e))
m()
```
And when I execute `python3 x.py -e a='b c'` I got `'a=b c'` . See that quotes around 'b c' are removed.

**Comment by lukaszachy** [comment]
Or shell ;) https://stackoverflow.com/questions/55857814/inner-quotes-of-string-being-removed-when-passed-as-an-argument

**Comment by psss** [comment]
Yes, shell strips the quotes. The current environment variables implementation supports providing multiple variables in a single option:

    tmt run -e "X=1 Y=2"

In order to parse multiple variables we do a `shlex.split()` on the `--environment` option content which causes the problem. To make working with current implementation it's possible to use this:

    tmt run --environment "BZLIST='716540 771869'"

We could also consider supporting only one variable definition per one ``--environment`` option. Not sure about this. @lukaszachy, what do you think?

**Comment by juk** [comment]
Hi Petr, thank you for explanation. 

I think current behavior makes sense and updating documentation with examples like you mention above should be sufficient.

**Comment by lukaszachy** [comment]
> We could also consider supporting only one variable definition per one `--environment` option. Not sure about this. @lukaszachy, what do you think?

No please. Once one realizes how to do the quoting it works as intended.

**Comment by juk** [comment]
> 

+1 For some reason i thought --environment expects single variable

**Comment by psss** [comment]
Ok, proposing a spec update in #974.
